[build]
  command = "pnpm install --no-frozen-lockfile && pnpm build"
  publish = ".next"

[dev]
  command = "pnpm dev"
  port = 3000
  targetPort = 3000
  framework = "next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
